spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_size: 5
        default_batch_fetch_size: 100

  redis:
    host: localhost
    port: 6379